### ISSUE TITLE
stack-build.sh fails with error msg

### ISSUE THREAD

**Issue by stedi67** [Tehnix/miso-isomorphic-stack#4]
fatal: cabal-install program /home/std/.stack/snapshots/x86_64-linux/lts-9.21/8.0.2/bin/cabal does not support --allow-boot-library-installs (requires version 2.0.0.0 or newer)

Ubuntu 16.04 LTS, stack --version: Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0

To be more precise, stack-build.sh actually runs without error message but no JS is created due to above error.

**Comment by Tehnix** [comment]
I suspect this might be because I upgraded to the GHCJS which uses LTS 9.21. It worked fine on my own setup, but it probably has some minor issues across platforms I'd imagine.

Could you try using this `stack.yaml` for the frontend,

```yaml
resolver: lts-8.11
packages:
- '.'
- ../common

extra-deps:
  - miso-0.19.0.0
  # Settle on a more recent version of Servant with the backend.
  # NOTE: We are using <0.13 because later versions bumped the Aeson dependency.
  - servant-0.12.1
  - cabal-doctest-1.0.6
allow-newer: true

compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b
```

and this for common,

```yaml
resolver: lts-8.11
packages:
- '.'

extra-deps:
  - miso-0.19.0.0
  # Pin Aeson to the version the frontend uses.
  - aeson-1.1.1.0
  # Settle on a more recent version of Servant with the frontend/backend.
  # NOTE: We are using <0.13 because later versions bumped the Aeson dependency.
  - servant-0.12.1
  - cabal-doctest-1.0.6
  - phoityne-vscode-0.0.22.0
```
